# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KCC Fast Path
description: > # this means to ignore newlines until "baseurl:"
  Earn a transfer degree in 2 years. Kankakee Community College's Fast Path program takes the guesswork out of college so you can focus on being successful.
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  wdzajicek
# include:
#   - "_pages"
#   - "_posts"
exclude:
  - "gulpfile.js"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpconfig.yml"
  - "/docs/"
  - "yarn.lock"
  - "package-lock.json"
  - "assets/js/lazyload.js"
  - "assets/scss/main.scss"
